### ISSUE TITLE
想问一下原理

### ISSUE THREAD

**Issue by tianweicc** [qiuziGirl/stylelint-config-qiuzi#5]
老哥，想问一下你这个制作的原理，直接把规则放在npm里面就可以了么？不需要依赖什么的？配置什么的

**Comment by qiuziGirl** [comment]
相关规则，已经写在里面了。当然，你也可以在使用的项目中重写规则。
在使用项目中，只需要再安装 stylelint 依赖包即可，使用案例，可看我这个项目：https://github.com/qiuziGirl/qiuzi-hospital-admin
